-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 14:08:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peliculas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema peliculas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peliculas` DEFAULT CHARACTER SET utf8 ;
USE `peliculas` ;

-- -----------------------------------------------------
-- Table `peliculas`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`Director` (
  `idDirector` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idDirector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`Pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`Pelicula` (
  `idPelicula` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `resumen` VARCHAR(255) NULL,
  `anio` INT NULL,
  `Director_idDirector` INT NOT NULL,
  PRIMARY KEY (`idPelicula`, `Director_idDirector`),
  INDEX `fk_Pelicula_Director_idx` (`Director_idDirector` ASC) VISIBLE,
  CONSTRAINT `fk_Pelicula_Director`
    FOREIGN KEY (`Director_idDirector`)
    REFERENCES `peliculas`.`Director` (`idDirector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`Serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`Serie` (
  `idserie` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `ntemporadas` INT NOT NULL,
  `nepisodios` INT NOT NULL,
  PRIMARY KEY (`idserie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`Usuario` (
  `alias` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `celular` INT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `fechanacimiento` DATE NULL,
  PRIMARY KEY (`alias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`Contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`Contenido` (
  `idContenido` INT NOT NULL,
  `Pelicula_idPelicula` INT NULL,
  `Serie_idserie` INT NULL,
  PRIMARY KEY (`idContenido`CREATE TABLE `contenido` (
  `idContenido` int NOT NULL,
  `Pelicula_idPelicula` int DEFAULT NULL,
  `Serie_idserie` int DEFAULT NULL,
  PRIMARY KEY (`idContenido`),
  KEY `fk_Pelicula_has_Serie_Serie1_idx` (`Serie_idserie`),
  KEY `fk_Pelicula_has_Serie_Pelicula1_idx` (`Pelicula_idPelicula`),
  CONSTRAINT `fk_Pelicula_has_Serie_Pelicula1` FOREIGN KEY (`Pelicula_idPelicula`) REFERENCES `pelicula` (`idPelicula`),
  CONSTRAINT `fk_Pelicula_has_Serie_Serie1` FOREIGN KEY (`Serie_idserie`) REFERENCES `serie` (`idserie`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
),
  INDEX `fk_Pelicula_has_Serie_Serie1_idx` (`Serie_idserie` ASC) VISIBLE,
  INDEX `fk_Pelicula_has_Serie_Pelicula1_idx` (`Pelicula_idPelicula` ASC) VISIBLE,
  CONSTRAINT `fk_Pelicula_has_Serie_Pelicula1`
    FOREIGN KEY (`Pelicula_idPelicula`)
    REFERENCES `peliculas`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pelicula_has_Serie_Serie1`
    FOREIGN KEY (`Serie_idserie`)
    REFERENCES `peliculas`.`Serie` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`Transmision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`Transmision` (
  `Usuario_alias` VARCHAR(45) NOT NULL,
  `Contenido_idContenido` INT NOT NULL,
  `fechatransmision` DATETIME NOT NULL,
  PRIMARY KEY (`Usuario_alias`, `Contenido_idContenido`),
  INDEX `fk_Contenidos_has_Usuario_Usuario1_idx` (`Usuario_alias` ASC) VISIBLE,
  INDEX `fk_Transmision_Contenido1_idx` (`Contenido_idContenido` ASC) VISIBLE,
  CONSTRAINT `fk_Contenidos_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_alias`)
    REFERENCES `peliculas`.`Usuario` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transmision_Contenido1`
    FOREIGN KEY (`Contenido_idContenido`)
    REFERENCES `peliculas`.`Contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
